/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclientv5.chat;

import chatclientv5.util.UiUtil;
import java.util.Date;

/**
 *
 * @author yusij
 */
public class FriendChatFrame extends javax.swing.JFrame {

    /**
     * Creates new form FriendChatFrame
     *
     * @param friend
     */
    String friend;

    public FriendChatFrame(String friend) {
        initComponents();
        myinit(friend);
        this.friend = friend;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        messageTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgEditor = new javax.swing.JEditorPane();
        sandButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("聊天信息：");

        messageTextArea.setEditable(false);
        messageTextArea.setColumns(20);
        messageTextArea.setRows(5);
        messageTextArea.setWrapStyleWord(true);
        jScrollPane2.setViewportView(messageTextArea);

        jScrollPane1.setViewportView(msgEditor);

        sandButton.setText("发送");
        sandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sandButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sandButton)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandButtonActionPerformed
        String msg = msgEditor.getText();
        if (msg.trim().length() > 0) {
            messageTextArea.append(MainFrame.user + "\t" + new Date() + "\n" + msg
                    + "\n--------------------------------------------------------------------------------\n");
            msgEditor.setText("");
            for (int i = 0; i < 5; i++) {
                if (MainFrame.sander.write("ChatWithFriend\n" + friend + "\n" + msg).equalsIgnoreCase("ok")) {
                    break;
                }
                messageTextArea.append("消息发送失败，正在重试\n");
                if (4 == i) {
                    messageTextArea.append("消息发送失败，出现了问题\n");
                }
            }
        }
    }//GEN-LAST:event_sandButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MainFrame.chatFrameOpen.replace("friends:" + friend, false);
    }//GEN-LAST:event_formWindowClosing

    private void myinit(String friend) {
        UiUtil.setCenter(this);

        this.setTitle("Friend Chat:" + friend);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
        new Thread(new FriendBackgroudMessageChacker(this, friend)).start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTextArea messageTextArea;
    private javax.swing.JEditorPane msgEditor;
    private javax.swing.JButton sandButton;
    // End of variables declaration//GEN-END:variables
}
