/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatclientv5.chat;

import chatclientv5.util.UiUtil;
import java.util.Date;

/**
 *
 * @author yusij
 */
public class GroupChatFrame extends javax.swing.JFrame {

    /**
     * Creates new form GroupChatFrame
     */
    String group;

    GroupChatFrame(String group) {
        initComponents();
        this.group = group;
        myinit(group);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        msgTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        memberList = new javax.swing.JList<>();
        memberLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        msgEditor = new javax.swing.JEditorPane();
        sandButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("聊天记录：");

        msgTextArea.setEditable(false);
        msgTextArea.setColumns(20);
        msgTextArea.setRows(5);
        msgTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(msgTextArea);

        memberList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(memberList);

        memberLabel.setText("群组成员：0");

        jScrollPane3.setViewportView(msgEditor);

        sandButton.setText("发送");
        sandButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sandButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(memberLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(sandButton)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(memberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sandButton)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sandButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sandButtonActionPerformed
        String msg = msgEditor.getText();
        if (msg.trim().length() > 0) {
            msgTextArea.append(MainFrame.user + "\t" + new Date() + "\n" + msg
                    + "\n--------------------------------------------------------------------------------\n");
            msgEditor.setText("");
            for (int i = 0; i < 5; i++) {
                if (MainFrame.sander.write("ChatWithGroup\n" + group + "\n" + msg).equalsIgnoreCase("ok")) {
                    break;
                }
                msgTextArea.append("消息发送失败，正在重试\n");
                if (4 == i) {
                    msgTextArea.append("消息发送失败，出现了问题\n");
                }
            }
        }
    }//GEN-LAST:event_sandButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        MainFrame.chatFrameOpen.replace("groups:" + group, false);
    }//GEN-LAST:event_formWindowClosing

    private void myinit(String group) {
        UiUtil.setCenter(this);

        this.setTitle("Group Chat:" + group);
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        this.setVisible(true);
        new Thread(new GroupMessageChacker(this, group)).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    javax.swing.JLabel memberLabel;
    javax.swing.JList<String> memberList;
    private javax.swing.JEditorPane msgEditor;
    javax.swing.JTextArea msgTextArea;
    private javax.swing.JButton sandButton;
    // End of variables declaration//GEN-END:variables
}
